# Warning: only edit this file inside the images git repository.
# If you are looking at this file in your root directory on your computer, editing it does nothing.

# The image will be at ghcr.io/yourusername/name
name: amy-os

# The native container image to build on top of
# Warning: Non-uBlue images might function unexpectly
base-image: ghcr.io/ublue-os/silverblue-main

# What fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated
# to the next major version assuming the image you're using as your base container
# builds with the tag (all uBlue images do this).
fedora-version: 38

# This description will be visible in the container metadata
description: Astro's custom version of Fedora Silverblue

# These scripts will be executed during the container build
# Place scripts in scripts/ and put the corresponding filename here
scripts:
#  - example.sh

# a list of urls of .repo files that should be added to your system
# this is the proper way to add copr repos to your image
extrarepos:
  # example:
  # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-37/atim-starship-fedora-37.repo

# These rpms will be installed from the fedora repository
# using rpm-ostree and will be preinstalled in the final image
rpms:
  # needed for yafti (the first boot installer) (remove if you're not using yafti)
  - python3-pip
  - libadwaita # libadwaita comes with silverblue, but not with other flavors
  # add your own below
  - firewall-config
  - gparted
  - kdeconnectd
  - langpacks-en
  - neofetch
  - neovim
  - sushi
  - tmux
  - util-linux-user
  - virt-manager
  - zsh

# These Flatpaks (from flathub) will be available for install on boot
# this is just an example selection.
# If you leave this empty you can use yafti for post-boot installation
flatpaks:
  - com.bitwarden.desktop
  - com.brave.Browser
  - com.discordapp.Discord
  - com.github.k4zmu2a.spacecadetpinball
  - com.github.micahflee.torbrowser-launcher
  - com.github.tchx84.Flatseal
  - com.github.wwmm.easyeffects
  - com.obsproject.Studio
  - com.spotify.Client
  - com.stremio.Stremio
  - com.valvesoftware.Steam
  - im.riot.Riot
  - io.github.hakuneko.HakuNeko
  - io.gitlab.librewolf-community
  - io.mpv.Mpv
  - net.davidotek.pupgui2
  - net.lutris.Lutris
  - network.loki.Session
  - org.audacityteam.Audacity
  - org.blender.Blender
  - org.duckstation.DuckStation
  - org.fedoraproject.MediaWriter
  - org.gimp.GIMP
  - org.gnome.Extensions
  - org.kde.kdenlive
  - org.libreoffice.LibreOffice
  - org.qbittorrent.qBittorrent
  - org.signal.Signal
  - org.standardnotes.standardnotes
  - org.telegram.desktop
  - org.videolan.VLC
  - org.yuzu_emu.yuzu
